<?php include 'header.php'; ?>

<!-- Attendance Report Content -->
<div class="attendance-content">

    <!-- Back Button and View Toggle -->
    <div class="report-header-actions mb-3">
        <div class="report-back-section">
            <a href="attendance.php" class="btn-back-report">
                <i class="fas fa-arrow-left"></i>
                <span>Back to Attendance</span>
            </a>
        </div>
        <div class="view-toggle-buttons">
            <button class="btn-view-toggle active" id="listViewBtn" data-view="list">
                <i class="fas fa-list"></i>
                <span>List View</span>
            </button>
            <button class="btn-view-toggle" id="calendarViewBtn" data-view="calendar">
                <i class="fas fa-calendar-alt"></i>
                <span>Calendar View</span>
            </button>
        </div>
    </div>

    <!-- Calendar View Section -->
    <div class="calendar-view-container" id="calendarViewSection" style="display: none;">
        <!-- Calendar Section (Left Side) -->
        <div class="calendar-main-section">
            <!-- Calendar Header -->
            <div class="calendar-header">
                <div class="calendar-nav">
                    <button class="calendar-nav-btn" id="calendarPrevMonth">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <div class="calendar-month-year">
                        <span id="calendarMonthYear">November 2025</span>
                    </div>
                    <button class="calendar-nav-btn" id="calendarNextMonth">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
            </div>

            <!-- Calendar Grid -->
            <div class="calendar-grid-wrapper">
                <div class="calendar-grid" id="attendanceCalendarGrid">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Right Side Statistics Cards -->
        <div class="calendar-stats-sidebar">
            <div class="stat-card-calendar stat-present-card">
                <div class="stat-card-icon">
                    <i class="fas fa-check-circle"></i>
                </div>
                <div class="stat-card-content">
                    <div class="stat-card-label">Present</div>
                    <div class="stat-card-value" id="calendarStatPresent">22</div>
                </div>
            </div>
            <div class="stat-card-calendar stat-absent-card">
                <div class="stat-card-icon">
                    <i class="fas fa-times-circle"></i>
                </div>
                <div class="stat-card-content">
                    <div class="stat-card-label">Absent</div>
                    <div class="stat-card-value" id="calendarStatAbsent">2</div>
                </div>
            </div>
            <div class="stat-card-calendar stat-late-card">
                <div class="stat-card-icon">
                    <i class="fas fa-clock"></i>
                </div>
                <div class="stat-card-content">
                    <div class="stat-card-label">Late</div>
                    <div class="stat-card-value" id="calendarStatLate">3</div>
                </div>
            </div>
            <div class="stat-card-calendar stat-halfday-card">
                <div class="stat-card-icon">
                    <i class="fas fa-clock-half"></i>
                </div>
                <div class="stat-card-content">
                    <div class="stat-card-label">Half Day</div>
                    <div class="stat-card-value" id="calendarStatHalfday">1</div>
                </div>
            </div>
        </div>
    </div>

    <!-- List View Section -->
    <div id="listViewSection">
        <!-- Table Header -->
        <div class="table-header-card">
            <div class="table-header-content">
                <h3 class="table-title">
                    <i class="fas fa-calendar-alt"></i>
                    <span>Monthly Attendance Record</span>
                </h3>
                <div class="table-actions">
                    <!-- Export Dropdown -->
                    <div class="dropdown export-dropdown">
                        <button class="btn-action btn-export-dropdown" type="button" id="reportExportDropdownBtn">
                            <i class="fas fa-download"></i>
                            <span>Export</span>
                            <i class="fas fa-chevron-down"></i>
                        </button>
                        <div class="dropdown-menu export-dropdown-menu" id="reportExportDropdownMenu">
                            <a href="#" class="dropdown-item export-option" data-format="excel">
                                <i class="fas fa-file-excel"></i>
                                <span>Export as Excel</span>
                            </a>
                            <a href="#" class="dropdown-item export-option" data-format="csv">
                                <i class="fas fa-file-csv"></i>
                                <span>Export as CSV</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Monthly Attendance Table -->
        <div class="report-table-section">
            <div class="table-wrapper">
                <table id="attendanceReportTable" class="attendance-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Shift</th>
                        <th>Clock In</th>
                        <th>Clock Out</th>
                        <th>Working Hours</th>
                        <th>Status</th>
                        <th>Message</th>
                        <th>Message Time</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Sample Data -->
                    <tr>
                        <td>01/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:15 pm</td>
                        <td>5:00 am</td>
                        <td>11.75</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>02/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:20 pm</td>
                        <td>5:00 am</td>
                        <td>11.67</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>03/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:00 pm</td>
                        <td>5:00 am</td>
                        <td>12.00</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>04/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td><span class="badge badge-absent">Absent</span></td>
                        <td>Medical emergency</td>
                        <td>04/11/2025 9:30 am</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>05/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:30 pm</td>
                        <td>5:00 am</td>
                        <td>11.5</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>06/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:45 pm</td>
                        <td>-</td>
                        <td>-</td>
                        <td><span class="badge badge-late">Late</span></td>
                        <td>Traffic jam</td>
                        <td>06/11/2025 6:15 pm</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>07/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:10 pm</td>
                        <td>5:00 am</td>
                        <td>11.83</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>08/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:25 pm</td>
                        <td>5:00 am</td>
                        <td>11.58</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>09/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td><span class="badge badge-absent">Absent</span></td>
                        <td>Family emergency</td>
                        <td>09/11/2025 8:00 am</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>10/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>6:00 pm</td>
                        <td>-</td>
                        <td>-</td>
                        <td><span class="badge badge-late">Late</span></td>
                        <td>Personal work</td>
                        <td>10/11/2025 6:30 pm</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>11/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:15 pm</td>
                        <td>5:00 am</td>
                        <td>11.75</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>12/11/2025</td>
                        <td>A (8:00 pm - 5:00 am)</td>
                        <td>5:20 pm</td>
                        <td>5:00 am</td>
                        <td>11.67</td>
                        <td><span class="badge badge-present">On Time</span></td>
                        <td>-</td>
                        <td>-</td>
                        <td>
                            <button class="btn-view-report" data-bs-toggle="modal"
                                data-bs-target="#viewAttendanceDetailModal">
                                <i class="fas fa-eye"></i>
                                <span>View / Edit</span>
                            </button>
                        </td>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<!-- View Attendance Detail Modal -->
<div class="modal fade" id="viewAttendanceDetailModal" tabindex="-1" aria-labelledby="viewAttendanceDetailModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="viewAttendanceDetailModalLabel">
                    <span>View / Edit Attendance Details</span>
                </h5>
                <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="viewAttendanceDetailForm">
                    <!-- Attendance Information Card -->
                    <div class="leave-info-card mb-4">
                        <div class="leave-info-header">
                            <span>Attendance Information</span>
                        </div>

                        <div class="leave-details-grid">
                            <!-- Date -->
                            <div class="leave-detail-item">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-calendar"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Date</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceDate">01/11/2025</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Shift -->
                            <div class="leave-detail-item">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Shift</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceShift">A (8:00 pm - 5:00 am)</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Working Hours -->
                            <div class="leave-detail-item">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-hourglass-half"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Working Hours</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceHours">11.75</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Status -->
                            <div class="leave-detail-item">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-check-circle"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Status</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceStatus"><span
                                                class="badge badge-present">Present</span></span>
                                    </div>
                                </div>
                            </div>

                            <!-- Message -->
                            <div class="leave-detail-item full-width">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-comment-dots"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Message</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceMessage">-</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Message Time -->
                            <div class="leave-detail-item full-width">
                                <div class="detail-icon-wrapper">
                                    <i class="fas fa-clock"></i>
                                </div>
                                <div class="detail-content-wrapper">
                                    <label class="detail-label">Message Time</label>
                                    <div class="detail-value-box">
                                        <span id="viewAttendanceMessageTime">-</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Clock In/Out Section -->
                    <div class="admin-comment-card">
                        <div class="admin-comment-header">
                            <span>Clock In / Clock Out</span>
                        </div>
                        <div class="admin-comment-content">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="viewClockIn" class="form-label text-dark fw-bold mb-2">Clock In</label>
                                    <input type="time" class="form-control admin-comment-textarea" id="viewClockIn"
                                        value="17:15">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="viewClockOut" class="form-label text-dark fw-bold mb-2">Clock
                                        Out</label>
                                    <input type="time" class="form-control admin-comment-textarea" id="viewClockOut"
                                        value="05:00">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="saveAttendanceDetailBtn">
                    <i class="fas fa-save"></i>
                    <span>Save Changes</span>
                </button>
            </div>
        </div>
    </div>
</div>

<?php include 'footer.php'; ?>